### ISSUE TITLE
 there is a noise

### ISSUE THREAD

**Issue by awtmeng** [kopiro/siriwave#19]
If write the code, there is a noise
`analyser.connect(ctx.destination);`
in mac（10.13 ）chrome browser，why？

What effect does it have to get rid of it？

`var ctx = new (window.AudioContext || window.webkitAudioContext)();`
`var analyser = ctx.createAnalyser();`
`//analyser.connect(ctx.destination);`
`analyser.fftSize = 2048;`

**Comment by kopiro** [comment]
@awtmeng what do you mean with "there is a noise" ?

**Comment by seriousben** [comment]
There is some strange feedback in the audio when using the audioContext example.

**Comment by seriousben** [comment]
Not using a new `audioContext` fixed this issue.
