### ISSUE TITLE
Unable to work from a webpack

### ISSUE THREAD

**Issue by Prithiraj** [kopiro/siriwave#23]
I use Quasar/Vuejs,

The earlier version used to work well but it failed with this version.

`import SiriWave from 'siriwave'`

```js
 methods: {
    initialized () {
      this.siriWave = new SiriWave({
        container: this.$refs['siri'],
        width: window.innerWidth,
        height: window.innerHeight * 0.12
      })
    }
  },
  mounted () {
    this.initialized()
  }
}
```

This throws an error telling SiriWave is not a constructor:

`[Vue warn]: Error in mounted hook: "TypeError: siriwave__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor"`

and

`TypeError: siriwave__WEBPACK_IMPORTED_MODULE_1___default.a is not a constructor`

**Comment by kopiro** [comment]
Hi @Prithiraj, now it should work.
Version 1.2.0
