### ISSUE TITLE
Wave reuse problem

### ISSUE THREAD

**Issue by denshest** [kopiro/siriwave#29]
Hello
I use your library and encountered a problem. I use to draw the waves when talking (using a microphone)
After I stopped recording and started recording it again, the waves start to twitch
Can you tell me how to fix this?

On this demo page you can see it. Just press the “Record” button and the “Stop” button several times.

https://siriwavejs.herokuapp.com/

I’m really looking forward to the answer, as I use this library for my university project, which will be in two weeks

**Comment by kopiro** [comment]
Hello! 

If you are connecting the wave to a continue-like source (microphone), try using `wave.amplitude = X` instead of using the interpolated method `setAmplitude`.

**Comment by denshest** [comment]
Thanks for your reply!
But unfortunately, the wave still twitches
The amplitude has become normal, but the wave itself continues to twitch anyway ...

**Comment by denshest** [comment]
I recorded a screencast for you, so that you understand the essence of the problem. I can attach the code that is responsible for drawing the wave.
[Screencast](https://youtu.be/OJdIPHXYF3U)

**Comment by kopiro** [comment]
Let's have a chat - you can reach me on https://kopiro.it/telegram

**Comment by denshest** [comment]
Oke, I sent a message to you

**Comment by myorangeca** [comment]
and...what was the outcome of the chat?

**Comment by kopiro** [comment]
Hey @myorangeca - it was something on its client-side code, specifically regarding the attach to the AudioAnalyzer
