### ISSUE TITLE
Module import does not work with Typescript

### ISSUE THREAD

**Issue by jkovzels** [kopiro/siriwave#31]
Hi @kopiro Thank you for creating an amazing library. I was trying to use it my Typescript application with `import SiriWave from 'siriwave';` but I get `Cannot find module 'siriwave ts(2307)'. ` literally with any `compilerOptions.module` variants in tsconfig.ts.

Typescript module resolution gives me the following:
```
======== Resolving module 'siriwave' from 'c:/Projects/tstest/app.ts'. ========
Explicitly specified module resolution kind: 'NodeJs'.
Loading module 'siriwave' from 'node_modules' folder, target file type 'TypeScript'.
Found 'package.json' at 'c:/Projects/tstest/node_modules/siriwave/package.json'.
'package.json' does not have a 'typesVersions' field.
File 'c:/Projects/tstest/node_modules/siriwave.ts' does not exist.
File 'c:/Projects/tstest/node_modules/siriwave.tsx' does not exist.
File 'c:/Projects/tstest/node_modules/siriwave.d.ts' does not exist.
'package.json' does not have a 'typings' field.
'package.json' does not have a 'types' field.
'package.json' does not have a 'main' field.
File 'c:/Projects/tstest/node_modules/siriwave/index.ts' does not exist.
File 'c:/Projects/tstest/node_modules/siriwave/index.tsx' does not exist.
File 'c:/Projects/tstest/node_modules/siriwave/index.d.ts' does not exist.
Directory 'c:/Projects/tstest/node_modules/@types' does not exist, skipping all lookups in it.
Directory 'c:/Projects/node_modules' does not exist, skipping all lookups in it.    
Directory 'c:/node_modules' does not exist, skipping all lookups in it.
Loading module 'siriwave' from 'node_modules' folder, target file type 'JavaScript'.
Found 'package.json' at 'c:/Projects/tstest/node_modules/siriwave/package.json'.
'package.json' does not have a 'typesVersions' field.
File 'c:/Projects/tstest/node_modules/siriwave.js' does not exist.
File 'c:/Projects/tstest/node_modules/siriwave.jsx' does not exist.
'package.json' does not have a 'main' field.
File 'c:/Projects/tstest/node_modules/siriwave/index.js' does not exist.
File 'c:/Projects/tstest/node_modules/siriwave/index.jsx' does not exist.
Directory 'c:/Projects/node_modules' does not exist, skipping all lookups in it.
Directory 'c:/node_modules' does not exist, skipping all lookups in it.
======== Module name 'siriwave' was not resolved. ========
```
As a workaround I have added `"main": "dist/siriwave.js"` to `package.json` but I'm not sure that this is the way to go with rollup.js compilation. Meaning I do not know if rollup.js js generates package.json for you or not. Any suggestions on how to make the library usable in Typescript in the sane way?

**Comment by xueyongg** [comment]
Is there any update for this? Thanks @jkovzels for the workaround! It works for me too.

**Comment by jkovzels** [comment]
FYI @xueyongg I ended up forking the library and made some changes to build config and added .d.ts file and later changed the library functionally quite a bit, so that it works in nodejs environment. So I can not recommend using my fork, but taking a look at the rollupjs config and .d.ts file can be helpful. I do not have time to create pull request.

**Comment by danieldanielecki** [comment]
Bump, same issue @kopiro

**Comment by lbarthon** [comment]
You just have to wait for the next release, he migrated the library to typescript

**Comment by kopiro** [comment]
@danieldanielecki can you try with the latest version?

**Comment by kopiro** [comment]
https://github.com/kopiro/siriwave/releases/tag/v2.0.0

**Comment by danieldanielecki** [comment]
@kopiro can't find in the release `d.ts` files, when installing `npm i siriwave` I'm getting:

```
Try `npm install @types/siriwave` if it exists or add a new declaration (.d.ts) file containing `declare module 'siriwave';
```

and/or

```
error TS7016: Could not find a declaration file for module 'siriwave'
```

Anyone else got a luck? cc: @lbarthon, @xueyongg, @jkovzels

**Comment by lbarthon** [comment]
I'm almost certain it had `.d.ts` files, I'm not sure of what happened with them :/

**Comment by kopiro** [comment]
Sadly I know what happened to them... there is a bug in the `rollup-plugin-typescript` library. I have to generate d.ts files separately. I'm gonna fix it and publish probably today!

**Comment by kopiro** [comment]
Hey, do you mind checking `master` version before I publish a new version? You should be able test it using `npm install https://github.com/kopiro/siriwave` :)

**Comment by Daskus1** [comment]
> Hey, do you mind checking `master` version before I publish a new version? You should be able test it using `npm install https://github.com/kopiro/siriwave` :)

I just tried it, but it does not seem to work for me. With `import SiriWave from 'siriwave'` still get `Cannot find module 'siriwave'`. 
I also checked the `siriwave` folder `node_modules` and there is just `LICENCE`, `README.md` and `package.json`.

**Comment by kopiro** [comment]
Okay, fixed it now: 

![image](https://user-images.githubusercontent.com/839700/86832060-fa4a7600-c097-11ea-90fb-fe2f00b823ca.png)

**Comment by kopiro** [comment]
I'm publishing it :)

**Comment by Daskus1** [comment]
Seems to work now, thanks! 
But there is still a small issue: The `CurveStyle` enum is only declared in `index.d.ts` and not exported, thus can not be used when constructing a `SiriWave` object:
```
this.waveCtrl = new SiriWave({
	container: document.body,
	style: CurveStyle.ios  // Cannot find name 'CurveStyle'.
});
```
Prepending `export` to `declare enum CurveStyle` in `index.d.ts` should fix the issue.

**Comment by kopiro** [comment]
Hey, I think you can just use the string there.

**Comment by Daskus1** [comment]
I use typescript with strict option, thus the compiler does not like that. I could of course add a ts-ignore but with the ebum it would be cleaner.

**Comment by danieldanielecki** [comment]
This issue should've been closed, @kopiro it's working - many, many thanks!
