### ISSUE TITLE
How to Integrate siriwave with audio/mp3 file

### ISSUE THREAD

**Issue by timi-codes** [kopiro/siriwave#33]
Maybe something around this
```
const waveInstance = new SiriWave({
      container: wave.current,
      speed: 0.02,
      cover: true
 });
waveInstance.setAudioUrl('url');
```

**Comment by lbarthon** [comment]
Maybe you can combine it with howler?

**Comment by kopiro** [comment]
Hey! This library is purely graphical, so I don't it makes sense to add an API to read an Audio. There is a working demo here anyway: https://github.com/kopiro/siriwave/issues/45
