### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by semmel** [kopiro/siriwave#45]
This [demo](https://jsitor.com/PPQtOp9Yp) is a modernised version of the [old demo](https://github.com/husenxce/siriwaveDemo). 

It does not use the deprecated `ScriptProcessorNode` API. Also I attempted to explain in the comments how `speed` and `frequency` can be calculated from an audio source signal.

Would be great that could be integrated into this project.

Edit:
Does not run in Safari, because I did not polyfill `requestIdleCallback`, which however would be easy.

**Comment by kopiro** [comment]
Nice, I'm gonna add it to the README
