### ISSUE TITLE
Curve style colors inverted

### ISSUE THREAD

**Issue by Daskus1** [kopiro/siriwave#49]
Following the documentation style: `"ios"` should draw the "simple" sinus wave, whereas `"ios9"` should draw the overlapping filled waves.
Using the latest version this behavior seems to be inverted, causing also the problem of not being able to change the color of the default wave at runtime.

Here a stackblitz example that reproduces the issue: [https://stackblitz.com/edit/typescript-iays7f?file=index.html](https://stackblitz.com/edit/typescript-iays7f?file=index.html)

**Comment by kopiro** [comment]
Thanks, fixed in https://github.com/kopiro/siriwave/commit/b430e11f06e95dc0387bc400d4097b703f8a869d

**Comment by kopiro** [comment]
Released 2.0.3 with this fix
