### ISSUE TITLE
Idea: dispose() method

### ISSUE THREAD

**Issue by semmel** [kopiro/siriwave#54]
In it's constructor SiriWave mutates the DOM by appending a `<canvas>` child to the target container DOM element. 
Would it not be nice to have some `dispose()` method (i.e. something like a destructor) which reverses the effects of the constructor?

Basically such a method just would have to
```javascript
dispose() {
   this.stop();
   this.canvas.remove();
   // But also: what if this instance is (wrongly) called again by the user?
   // ... throw on next start() ?
}
```

My use case:
I find myself destroying and creating new SiriWaves when my app's layout (i.e. the container element size) changes. So that width and height of the canvas are properly reset for the line animation. However unused canvas elements (owned by probably already garbage-collected SiriWaves) break my layout.

**Comment by kopiro** [comment]
Nice idea! I'll try to implement it tomorrow!

**Comment by kopiro** [comment]
@semmel what do you think?

**Comment by ikupenov** [comment]
Was just looking for this, thanks!
