### ISSUE TITLE
amplitudes remain zero when too much time elapses between new SiriWave() and start()

### ISSUE THREAD

**Issue by semmel** [kopiro/siriwave#56]
### Demo:
In the [demo](https://jsitor.com/0kImE4O4h) in the left and right containers two otherwise identical SiriWave instances are created at startup time. The left is run (with random data) right away, while the right gets run but on a click of the button below.

If more than *a couple of seconds* elapse before the right SiriWave instance is started, it's y amplitudes *remain zero and just a white zero line is drawn*. On the other hand if you click the button quickly after loading, both visualisations behave similar.

I have not found this to be the case for the "ios" visualisation.

### Analysis
I guess it's the `this.spawnAt` timestamp in `ios9curve.ts` which is set once at construction time and then becomes relatively small compared to the timestamp at the later point when `start()` and subsequently `draw()` is called. Thus in the `draw()` method the time comparison in the for loop always decreases `this.amplitudes[ci]` which in turn causes the `_ypos()` method to always compute 0.

### Quick fix
Respawn all curves in `start()` by adding a line in `index.ts`:

```javascript
start() {
        this.phase = 0;
        // Ensure we don't re-launch the draw cycle
        if (!this.run) {
            this.run = true;
            this.curves.map(curve => curve.respawn());  // <--- Added this line
            this.startDrawCycle();
        }
    }
```

Note that with this fix for `autostart: true`, `respawn` is called twice in a row: 
- from the curve constructor and
- from SiriWave constructor again via `SiriWave.start()` 

![Screenshot 2020-12-17 at 19 47 44](https://user-images.githubusercontent.com/296476/102529854-cb054f80-40a0-11eb-9f3a-a7488984578e.png)

**Comment by kopiro** [comment]
https://github.com/kopiro/siriwave/pull/58/files

**Comment by kopiro** [comment]
Please check version 2.2 to check if the issue is solved on your side.

**Comment by semmel** [comment]
New version works perfect!
Thanks a lot!
❤️
