### ISSUE TITLE
In style "ios", setting color in curve definition doesn't affect the curve.

### ISSUE THREAD

**Issue by SmitMaruti** [kopiro/siriwave#61]
I want to have different colors for the curves, I am using the following curve definition 
`[
        {
            attenuation: -2,
            lineWidth: 1,
            opacity: 0.6,
            color: "229,231,233",
        },
        {
            attenuation: 2,
            lineWidth: 1,
            opacity: 0.8,
            color: "255,159,148",
        },
        {
            attenuation: 1,
            lineWidth: 1.5,
            opacity: 1,
            color: "109,111,189",
        },
    ]`

But the wave is shown in default white color only.

**Comment by kopiro** [comment]
Fixed in: https://github.com/kopiro/siriwave/issues/61
