### ISSUE TITLE
Not the same rendering between browsers

### ISSUE THREAD

**Issue by michaelgrc** [kopiro/siriwave#9]
Hi there,
first thank you very much for this outstanding plugin.
Here's my issue : I don't have the same render between two browsers, the wave look thinner on Chrome then on Firefox.

On Firefox :
![capture d ecran 2015-09-11 a 15 32 57](https://cloud.githubusercontent.com/assets/3244263/9816055/ba637c40-589a-11e5-82b9-5e2fa08b4404.png)

On Chrome :
![capture d ecran 2015-09-11 a 15 33 08](https://cloud.githubusercontent.com/assets/3244263/9816066/cfb583ae-589a-11e5-8a08-603719f33bfb.png)

Is there any way to obtain a 1px thickness on the both cases ?
Thank you very much.

**Comment by kopiro** [comment]
Which version of Chrome do you use?

**Comment by michaelgrc** [comment]
I do use Chrome 45.0 and I'm on a Mac

**Comment by michaelgrc** [comment]
I don't understand what is going on but it became thin on Firefox too.
Here are my current renderings : 

- Safari 6.2
![capture d ecran 2015-09-15 a 16 22 12](https://cloud.githubusercontent.com/assets/3244263/9879043/f4e2dcd4-5bc5-11e5-8322-a8ea280c7252.png)

- Firefox 40.0
![capture d ecran 2015-09-15 a 16 22 40](https://cloud.githubusercontent.com/assets/3244263/9879060/08ae414a-5bc6-11e5-9e8d-4d94d11c7fec.png)

- Chrome 45.0
![capture d ecran 2015-09-15 a 16 23 19](https://cloud.githubusercontent.com/assets/3244263/9879071/196b3934-5bc6-11e5-9137-5978317131a4.png)

It only seems to work properly on Safari.
Do you have any clue ?

Thanks a lot

**Comment by kopiro** [comment]
Do you have a Retina screen?

**Comment by michaelgrc** [comment]
no I doesn't ...

**Comment by lastguest** [comment]
It seems that it can be something related to GPU accelerated canvas rendering.
Check GPU acceleration status on chrome://gpu/

What is your video card model? (or on what kind of Mac are you trying?)

**Comment by michaelgrc** [comment]
Hi lastguest,
truly sorry for the delayed answer
I've a 2.9 GHz Intel Core i7 with Intel HD Graphics 4000 512 Mo for the video card.

I founded a solution buy changing this line on the script : 
`this._drawLine(1, 'rgba(' + this.color + ',1)', 1.15);`
instead of : 
`this._drawLine(1, 'rgba(' + this.color + ',1)', 1);`

With this solution I've the same render on Chrome , Safari and Firefox : 
![capture d ecran 2015-09-30 a 13 49 44](https://cloud.githubusercontent.com/assets/3244263/10192109/22d8f5dc-677a-11e5-949d-b2bae4bd6500.png)
It seems quite all right to me

BUT, I was able to try it on a retina screen and here is the render : 
Safari on retina screen : 
<img width="261" alt="safari_retina" src="https://cloud.githubusercontent.com/assets/3244263/10192123/486252c6-677a-11e5-896d-5bf60b381d4a.png">
Chrome on retina screen : 
<img width="259" alt="chrome_retina" src="https://cloud.githubusercontent.com/assets/3244263/10192128/4f64e250-677a-11e5-809c-14028d3ba333.png">

There's the same issue even with the 1.15 modification ... 
Do you have any idea ? Thank you very much

**Comment by kopiro** [comment]
Did you solved?

**Comment by kopiro** [comment]
It should be fixed now.
